FROM debian:stretch-slim
RUN set -ex; \
    apt-get update; \
    apt-get install -y \
        build-essential \
        automake \
        git \
        cmake \
        default-libmysqlclient-dev \
        libboost-all-dev \
        libev-dev \
        libjemalloc-dev \
        libmysql++-dev \
        pkg-config;\
    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
